# Estudo sobre incertezas em dados de poços

In [2]:
! pip install --upgrade uncertainties

Collecting uncertainties
  Downloading uncertainties-3.1.6-py2.py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 6.6 MB/s  eta 0:00:01
Requirement already satisfied: future in /home/carreira/anaconda3/lib/python3.9/site-packages (from uncertainties) (0.18.2)
Installing collected packages: uncertainties
Successfully installed uncertainties-3.1.6

In [6]:
! pip install lasio

Collecting lasio
  Downloading lasio-0.29-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: numpy in /home/carreira/anaconda3/lib/python3.9/site-packages (from lasio) (1.20.3)
Installing collected packages: lasio
Successfully installed lasio-0.29

In [2]:
# -*- coding: utf-8 -*-
import numpy as np
import scipy as sp
from scipy import signal
import pandas as pd
import lasio
import matplotlib.pyplot as plt

#modulos internos
import os,sys
sys.path.append('../modulos')
import imod
from imod import Statistical
from graficador import plotagem as plm2



#Configurando figura e o rc parameters
%config InlineBackend.figure_format='retina'
plt.rcParams["figure.figsize"] = (10,15)
plt.rc('text', usetex=True)
plt.rc('font', family='serif', size = 18)


from uncertainties import ufloat
from uncertainties.umath import *

from os import getcwd, listdir
from os.path import isfile, join

# Lendo os dados de entrada

In [12]:
#COT calculado via DRlog
cab = ['Depth','COT','DT','GR','NPHI','RHOB']
datareal = pd.read_csv('../saidas/1-ESS-120_resample_COT.txt', sep='\\s+',
                       skiprows=1, names = cab, usecols=(0,1,2,3,4,5))
df = pd.DataFrame(datareal)
print(len(df))
#separando as informações do dado em variáveis distintas
z = df[df.columns[0]]#prof
COT = df[df.columns[1]]
DT = df[df.columns[2]]#sonico
GR = df[df.columns[3]]#GR
NPHI = df[df.columns[4]]#neutrao
RHOB = df[df.columns[5]]#densidade

7340

In [15]:
df

          Depth       COT        DT        GR      NPHI      RHOB
0     4800.1046  5.400561  70.30501  157.6507  14.05369  2.616479
1     4800.3046  4.322480  73.25121  127.1674  11.76468  2.605533
2     4800.5046  4.061132  76.35267  119.7623  17.90119  2.585634
3     4800.7046  4.224416  78.27454  124.3640  21.43119  2.587109
4     4800.9046  4.050501  76.25685  119.4625  19.73067  2.608446
...         ...       ...       ...       ...       ...       ...
7335  6395.9046  5.417372  74.54109  158.4027  12.76359  2.693078
7336  6396.1046  5.417345  73.37498  158.4027  12.04690  2.707989
7337  6396.3046  5.417919  72.57875  158.4027  11.25337  2.676428
7338  6396.5046  5.418072  72.42371  158.4027  11.04827  2.661956
7339  6396.7046  5.418037  72.51006  158.4027  11.58292  2.664151

[7340 rows x 6 columns]

In [42]:
#Simulação COT Achilles:
cab = ['Depth','RHOB','Prod_1','Sed','PaleoBAT','Frac_areia','Idades','F_carbono','COma','rCO','qCO','COte','COT']
datasimu = pd.read_csv('../entradas/Simulacao_COT_3.las', sep='\\s+',
                       skiprows=44, names = cab, usecols=(0,1,2,3,4,5,6,7,8,9,10,11,12))
df_a = pd.DataFrame(datasimu)
print(len(df_a))
#separando as informações do dado em variáveis distintas
z_a = df_a[df_a.columns[0]]#prof
COT_a = df_a[df_a.columns[12]]#COT

8702

In [43]:
df_a

,Depth,RHOB,Prod_1,Sed,PaleoBAT,Frac_areia,Idades,F_carbono,COma,rCO,qCO,COte,COT
0,2062.5,0.71284,134.62163,9.16284,1285.70094,98.35779,62.29210,0.69417,0.17947,0.00821,0.09853,0.10674,0.28622
1,2063.0,0.71284,134.67885,9.16284,1284.22165,98.40674,62.29751,0.69562,0.17985,0.00797,0.09560,0.10356,0.28341
2,2063.5,0.71284,134.73668,9.16274,1282.72865,98.32983,62.30296,0.69708,0.18023,0.00835,0.10021,0.10856,0.28879
3,2064.0,0.71284,134.79462,9.16280,1281.23563,98.23161,62.30842,0.69854,0.18060,0.00884,0.10610,0.11495,0.29555
4,2064.5,0.71284,134.85264,9.16282,1279.74261,98.30800,62.31388,0.70002,0.18098,0.00846,0.10152,0.10998,0.29096
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8697,6411.0,2.57565,150.56350,4.92949,949.41663,88.42063,124.18510,1.19976,0.09134,0.05790,0.69476,0.75266,0.84400
8698,6411.5,2.57565,150.56350,4.92949,949.41663,88.42063,124.19524,1.19976,0.09134,0.05790,0.69476,0.75266,0.84400
8699,6412.0,2.57565,150.56350,4.92949,949.41663,88.42063,124.20539,1.19976,0.09134,0.05790,0.69476,0.75266,0.84400
8700,6412.5,2.57565,150.56350,4.92949,949.41663,88.42063,124.21553,1.19976,0.09134,0.05790,0.69476,0.75266,0.84400
8701,6413.0,2.57565,150.56350,4.92949,949.41663,88.42063,124.22567,1.19976,0.09134,0.05790,0.69476,0.75266,0.84400

In [46]:
# Selação do intervalo de relevância para redimensionamento dos vetores de entrada
df_a=df_a[(df_a['Depth'] > 4800.1) & (df_a['Depth'] < 6396.7)]

In [47]:
df_a

,Depth,RHOB,Prod_1,Sed,PaleoBAT,Frac_areia,Idades,F_carbono,COma,rCO,qCO,COte,COT
5476,4800.5,2.40662,124.38332,5.02340,1592.97984,91.72382,100.99374,0.47154,0.03835,0.04138,0.49657,0.53795,0.57630
5477,4801.0,2.41666,124.39233,5.02363,1592.66754,92.38205,101.00266,0.47171,0.03820,0.03809,0.45708,0.49517,0.53337
5478,4801.5,2.30242,124.52377,5.02340,1588.11675,93.12191,101.01186,0.47415,0.04030,0.03439,0.41269,0.44708,0.48738
5479,4802.0,2.42377,124.66650,5.02361,1583.19598,93.80345,101.02182,0.47681,0.03850,0.03098,0.37179,0.40278,0.44128
5480,4802.5,2.49365,124.80981,5.02340,1578.27511,90.82810,101.03177,0.47950,0.03763,0.04586,0.55031,0.59617,0.63381
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8664,6394.5,2.53217,150.56350,4.92949,949.41663,88.42063,123.85038,1.19976,0.09291,0.05790,0.69476,0.75266,0.84557
8665,6395.0,2.58544,150.56350,4.92949,949.41663,88.42063,123.86052,1.19976,0.09099,0.05790,0.69476,0.75266,0.84365
8666,6395.5,2.56679,150.56350,4.92949,949.41663,88.42063,123.87066,1.19976,0.09165,0.05790,0.69476,0.75266,0.84431
8667,6396.0,2.57648,150.56350,4.92949,949.41663,88.42063,123.88081,1.19976,0.09131,0.05790,0.69476,0.75266,0.84397
8668,6396.5,2.55147,150.56350,4.92949,949.41663,88.42063,123.89095,1.19976,0.09220,0.05790,0.69476,0.75266,0.84486

# Fazendo o Resample: